### ISSUE TITLE
BAS - Yeoman UI generator running issue

### ISSUE THREAD

**Issue by UladzislauYurhel** [SAP/yeoman-ui#532] opened 2021-03-25 11:25 UTC
Hi!

Recently we have successfully developed an extension which uses the Yeoman UI and could be run in VS Code properly as it was expected (and fields, divided by sections, can be filled by the user as well). But after the extension has been built (using the **vsce package**) and deployed into BAS, the generator during the command execution could not run itself and always failing with that message box:

![image](https://user-images.githubusercontent.com/81150486/112464601-bfe34f00-8d74-11eb-9729-9b8c77d81cc0.png)

**Local environment details**

- **OS:** Ubuntu 18.04 LTS
- **IDE:** VS Code 1.53.2
- **VS Code Extensions:** Application Wizard 1.1.57 (the newest version 1.1.59 as in BAS is not available for download)

P.S. After the Yeoman UI backend sources research (for a generator run), I've found that it may be somehow related to the generator metadata (src/yeomanui.ts:211), because if I understand correctly the `resolved` property could not be found here (src/yeomanui.ts:212).

This is really a blocker for the time being, maybe you can lead or give the right direction for that. Thanks!

**Comment by slavik-lvovsky** [comment] 2021-03-25 12:41
Hi,

Could you please send me the generator repo ?

Regards,
Slavik.

**Comment by UladzislauYurhel** [comment] 2021-03-25 13:14
Hi!

The actual repo is: https://github.wdf.sap.corp/XSA-Migration/xs-migration-cloud/tree/neo-tunnel-impl
The generators are implemented here: https://github.wdf.sap.corp/XSA-Migration/xs-migration-cloud/tree/neo-tunnel-impl/lib/bas/yeoman-generators
The execution of Yeoman UI with the related generator you can find here: https://github.wdf.sap.corp/XSA-Migration/xs-migration-cloud/blob/neo-tunnel-impl/extension.js

> Did you install the generator using npm link ?

Yes, I've also tried to do that before the extension is deployed. Nevertheless it works fine in the VS Code even without the npm link.

**Comment by UladzislauYurhel** [comment] 2021-03-25 14:22
Cannot see it there: 
![image](https://user-images.githubusercontent.com/81150486/112488512-a3eca700-8d8e-11eb-9ed4-f9001cf8bacb.png)

Best Regards,
Uladzislau.

**Comment by slavik-lvovsky** [comment] 2021-03-25 14:33
I suppose you do not get it also via yo cli, right ? 
Just run "yo" command in terminal please

**Comment by UladzislauYurhel** [comment] 2021-03-25 15:22
Yes, there is also no such thing there.

![image](https://user-images.githubusercontent.com/81150486/112497710-ea460400-8d96-11eb-9015-2e39c0fc26df.png)

**Comment by slavik-lvovsky** [comment] 2021-03-25 17:58
Ok, it means that the generator was not properly installed.
Just open terminal in the generator package.json directory and run "npm link" again.

**Comment by UladzislauYurhel** [comment] 2021-03-25 19:09
Thanks for the response, but it does not help. I cannot run `npm link` in the BAS directly (due to we have no sources there, only locally), so I tried to do that from the local project folder before I've built the extension for deployment into BAS. Still getting the same issue.

**Comment by slavik-lvovsky** [comment] 2021-03-25 19:38
There is no problem with yeoman-ui in BAS.
I have cloned your project and run "npm link" in yeoman-generators repository and got the migartion generator via "Run Generators" command. 
![migration-generators](https://user-images.githubusercontent.com/5508128/112533260-6ef24b80-8db2-11eb-8edc-29e2e5db3e93.png)

**Comment by UladzislauYurhel** [comment] 2021-03-25 20:09
Yeah, I understand that it works properly when you run it from the sources, but we have a bit another approach of how to run it.

1. Try to build an extension (`npm install && npm run build-ext`)
2. Deploy the created **.vsix** extension file and copy it to the workspace (/home/user/projects) in the BAS
3. Open the command pallet and choose `Plugin: Deploy plugin by Id` with the `local-dir:/home/user/projects` (or the root folder where vsix file is located) and press enter
4. Try to open command pallet again to find the `SAP - XS Migration` command and run it
5. You will get an error, but the main idea of generator running is the same as from the sources

So, an expected result is (from the VS Code):

![image](https://user-images.githubusercontent.com/81150486/112536826-fd6cca00-8dbe-11eb-8d97-21ae8259d1bf.png)

**Comment by slavik-lvovsky** [comment] 2021-03-26 06:40
Yo cli ,which is not developed by us, and yeoman-ui search for generators in the same locations. Both of them do not find your generator. The deployment process described above is related to your extension vsix but not to the generator.

Let's do another check. Go to viscose and in terminal execute: "npm root -g". You will get a path. Go to the path directory and check please that your generator is there.

**Comment by plazhbanov** [comment] 2021-03-26 07:13
Hi Slavik,

But we use the recommended [tool](https://www.npmjs.com/package/@sapse/business-application-studio-extension-management) to deploy the extension to BAS as described [here](https://github.wdf.sap.corp/pages/devx-wing/CookBook/extension-guides/04-Deploy-extension/#deploy-using-the-wex-cli)

As I see on the error call stack the issue happened in the yeoman-ui source code
![image](https://user-images.githubusercontent.com/10938337/112595662-c8db2b80-8e1b-11eb-9997-0fb4fecd7fa6.png)

Let's set up a call and discuss it in detail?

**Comment by slavik-lvovsky** [comment] 2021-03-26 07:31
Hi,

You can set a call with Tomer Epstein next week, I am currently on a sick leave till 4.4.2021.

Yes I understand, but the tool deploys only your extension not the generator.
Yeoman-ui fails (in a not user friendly way, we will improve it) because it was not able to find your generator.
You have checked that yo cli was not able to find it either.

I am not familiar with the deploy tool, but if it designed to deploy both extension and generator we should talk with the responsible team to find out why it does not work.

Yeoman-ui has it's bugs, but if yo cli does not work either the problem is in another place.

Please set a meeting with Tomer and he will help you to find the right solution.

**Comment by tomer-epstein** [comment] 2021-03-26 07:38
Closing this issue.
Internal jira ticket has been opened.

**Closed by tomer-epstein** 2021-03-26 07:38 UTC
